parameters:
    norzechowicz_ace_editor.json_form.resource: '@NorzechowiczAceEditor/form/div_layout_json.html.twig'
    norzechowicz_ace_editor.ace_form.resource: '@NorzechowiczAceEditor/form/div_layout_ace.html.twig'

services:
    Norzechowicz\AceEditorBundle\Form\Extension\AceEditor\Type\AceEditorType:
        autowire: true
        autoconfigure: true
        tags: 
            - { name: form.type, alias: ace_editor }

    Norzechowicz\AceEditorBundle\Form\Extension\JsonEditor\Type\JsonEditorType:
        autowire: true
        autoconfigure: true
        tags: 
            - { name: form.type, alias: json_editor }
