services:
    AceEditorBundle\Twig\Extension\AceEditorExtension:
        autowire: true
        autoconfigure: true
        arguments:
            - '%ace_editor.options.autoinclude%'
            - '%ace_editor.options.base_path%'
            - '%ace_editor.options.mode%'
#            - '%ace_editor.options.autoinclude_ace%'
#            - '%ace_editor.options.base_path_ace%'
#            - '%ace_editor.options.mode_ace%'
        tags:
            - { name: 'twig.extension' }

#    ace_editor.twig.ace_form_extension:
    ace_editor.twig.form_extension:
        alias: AceEditorBundle\Twig\Extension\AceEditorExtension
        public: true

    AceEditorBundle\Twig\Extension\JsonEditorExtension:
        autowire: true
        autoconfigure: true
        arguments:
            - '%ace_editor.options.autoinclude_json%'
            - '%ace_editor.options.base_path_json%'
        tags:
            - { name: 'twig.extension' }

    ace_editor.twig.json_form_extension:
        alias: AceEditorBundle\Twig\Extension\JsonEditorExtension
        public: true
